/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#include<LED.h>



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
int main(void)
{


	init(led_green);
	led_off(led_green);
	 RCC->AHB1ENR |= BV(0);
	 GPIOA->MODER &= ~(3 << (0 * 2));
	 GPIOA->PUPDR &= ~(3 << (0 * 2));
	 GPIOA->PUPDR |=  (1 << (0 * 2));

	uint8_t prev = 1;
	while(1)
	{
		uint8_t curr = (GPIOA->IDR & BV(0)) ? 1: 0;
		if(prev == 1 && curr == 0)
		{
			led_on(led_green);
			for(int i=0; i<200000; i++);
		}
		prev = curr;
	}
}

