/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

#include<stm32f407xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define BV(n) (1 << (n))

void intit(void);




void init(void)
{
	RCC->AHB1ENR 	|= BV(3);
	GPIOD->MODER 	&= ~(BV(25) | BV(27) | BV(29) | BV(31));
	GPIOD->MODER 	&= ~(BV(24) | BV(26) | BV(28) | BV(30));
	GPIOD->MODER 	|= BV(24) | BV(26) | BV(28) | BV(30);
	GPIOD->OTYPER 	&= ~(BV(12)| BV(13) | BV(14)| BV(15));
	GPIOD->OSPEEDR 	&= ~(BV(25)|BV(27)|BV(29)|BV(31));
	GPIOD->OSPEEDR 	&= ~(BV(24)| BV(26)|BV(28)|BV(30));
	GPIOD->PUPDR 	&= ~(BV(25)|BV(27)|BV(29)|BV(31));
	GPIOD->PUPDR 	&= ~(BV(24)|BV(26)|BV(28)|BV(30));
	//GPIOD->PUPDR 	|= BV(24)|BV(26)|BV(28)|BV(30);

}

int main(void)
{
    /* Loop forever */
	init();
	while(1){
		for(int i =1;i<=4;i++)
		{
			GPIOD->ODR = ((1<<i)-1) << 12;
			DelayMs(1000);
		}

		for(int i = 3;i>=0;i--)
		{
			GPIOD->ODR = ((1<<i)-1) << 12;
			DelayMs(1000);
		}
	}

}
