 /**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include<stm32f407xx.h>

#define BV(n)	(1 << (n))

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void led_init(void);

void led_init(void)
{
	RCC->AHB1ENR |= BV(3);
	RCC->AHB1ENR |= (1<<0);
	GPIOD->MODER |= BV(12 * 2);
	GPIOD->MODER &= ~(BV(12 * 2 + 1));
	GPIOA->MODER &= ~(3 << 0);
}

int main()
{
	led_init();
	while(1)
	{
		if(GPIOA->IDR & (1<<0))
		{
			GPIOD->ODR ^=(1<<12);
			DelayMs(1000);
		}


	}
}












